from setuptools import setup

setup(
    name = 'users',
    version = '1.0.0',
    description = 'This module contains methods for working with user authorization via bots.',
    py_modules = ['users'],
    package_dir = {'':'src'},
    author = 'Oleg Bervinov',
    author_email = 'unknown-312@ya.ru',
    long_description = open('README.md').read() + '\n\n' + open('CHANGELOG.md').read(),
    long_description_content_type = "text/markdown",
    url='https://github.com/obervinov/users-package',
    include_package_data=True,
    classifiers  = [
        'Development Status :: 4 - Beta',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        "License :: OSI Approved :: BSD License",
        'Intended Audience :: Developers',
        'Intended Audience :: Other Audience',
        'Intended Audience :: Science/Research',
        'Intended Audience :: Education',
        'Topic :: Text Processing',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: OS Independent',
    ],
    keywords = ['user', 'auth', 'secure'],
)