name: Create GitHub Release

on:
  workflow_run:
    workflows: ["Tests and Checks"]
    branches: [main]
    types: 
      - completed

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/create.release.yml@v1.0.4
