name: Tests and checks

on:
  push:
    branches:    
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  pylint:
    uses: obervinov/_templates/.github/workflows/pylint.yml@v1.0.2
  flake8:
    uses: obervinov/_templates/.github/workflows/flake8.yml@v1.0.2
  pytest:
    uses: obervinov/_templates/.github/workflows/pytest.yml@v1.0.2
  package-version:
    uses: obervinov/_templates/.github/workflows/version.yml@v1.0.2
