---
name: Tests and Checks

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'

jobs:
  pylint:
    uses: obervinov/_templates/.github/workflows/test.pylint.yml@v1.0.5
  verify-package:
    uses: obervinov/_templates/.github/workflows/verify.package.yml@v1.0.5
  verify-changelog:
    uses: obervinov/_templates/.github/workflows/verify.changelog.yml@v1.0.5
  pytest:
    uses: obervinov/_templates/.github/workflows/test.pytest-with-vault.yml@v1.0.5
